---
- name: update homebrew
  command: brew update
  when: ansible_os_family == 'Darwin'

- name: add taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - caskroom/fonts
  when: ansible_os_family == 'Darwin'
